### ISSUE TITLE
stop loss orders opened in a loop

### ISSUE THREAD

**Issue by doftorul** [Haehnchen/crypto-trading-bot#10]
If there is a open position and the watchdog is enabled, it does not check for the existence of a stop loss, it puts a new stop loss order over and over and over until the exchange throws a "too many stop loss positions"

**Comment by Haehnchen** [comment]
its a bug by the bitmex websocket libary. maybe i will replace it as its not really maintained: https://github.com/BitMEX/api-connectors/pull/285

**Comment by Haehnchen** [comment]
fixed with a patch: https://github.com/Haehnchen/crypto-trading-bot/commit/e50fa8c30fbfbee0839ae1a342a9e5c797326336
