### ISSUE TITLE
Pair Management - Twig Exception

### ISSUE THREAD

**Issue by Bitmasss** [Haehnchen/crypto-trading-bot#101]
Hello.

I've pulled the latest master and ran it using Docker. Input my API keys on binance for example and everything looks ok.

When using the pair management page, I get the following error:

```
crypto-trading-bot | Error parsing twig template /usr/src/app/templates/pairs.html.twig:
crypto-trading-bot | TwigException: Key "process" for object with keys "exchange, symbol, watchdogs, state, has_position, capital, strategies" does not exist.
crypto-trading-bot | Error parsing twig template /usr/src/app/templates/pairs.html.twig:
crypto-trading-bot | TwigException: Key "process" for object with keys "exchange, symbol, watchdogs, state, has_position, capital, strategies" does not exist.
```
Also the same for the candles page:

```
crypto-trading-bot | TwigException: Variable "period" does not exist.
crypto-trading-bot | Error parsing twig template /usr/src/app/templates/candle_stick_export.html.twig:
crypto-trading-bot | TwigException: Variable "candles" does not exist.
```

Any ideas?

Any help would be appreciated.
Thanks

**Comment by egisz** [comment]
I also have same problem, spent an hour trying to fix it, but it seems this is bug in recent twig module update. See this [ticket ](https://github.com/twigjs/twig.js/issues/679).

**Comment by Bitmasss** [comment]
Thanks @egisz that was exactly the problem. Rolled back and all fine now.

**Comment by Haehnchen** [comment]
also commited
