### ISSUE TITLE
 npm install  Connection timed out

### ISSUE THREAD

**Issue by xiongqi215** [Haehnchen/crypto-trading-bot#105]
when run npm install  --production, i get a error below:
`npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/bitfinexcom/bfx-api-node-util.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/bitfinexcom/bfx-api-node-util.git/': Failed to connect to github.com port 443: Connection timed out
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-02T09_59_11_756Z-debug.log`

i need some help

**Comment by Haehnchen** [comment]
local issues; not related to the project itself
