### ISSUE TITLE
Signals working - but not trading

### ISSUE THREAD

**Issue by goINTo425** [Haehnchen/crypto-trading-bot#106]
I have the same problem with #24 issues.
The signal is generated according to my custom strategy, but no order is generated.
Also, the strategies column is blank on the pairs page.
How can I solve it? Thanks in advance!

**Comment by kyrypto** [comment]
This issue is still happening. Using BitMex/BitMex Testnet, the strategies column is blank regardless of what's in the instance.js. Signals appear on the signals page, but the bot doesn't trade. This problem occurs even with the default configuration with the bitmex testnet.

**Comment by danipolo** [comment]
I'm experiencing the same problem. Signals show on the table but they don't trade. I've tried with Binance and Bitmex. Any of them work.

**Comment by mrseeker** [comment]
Note, the strategy must be inside the "trade" block. If not, then it does not watch for trade strategies and therefore never executes them.

**Comment by Wladastic** [comment]
It must be both, in the trade block and also not, otherwise the strategy is not even checked

**Comment by mrseeker** [comment]
Culprit might be this line:
https://github.com/Haehnchen/crypto-trading-bot/blob/9c31f4d0d73cac9a9a3bf0c6385c1e5fddbdf1af/src/modules/listener/tick_listener.js#L173

**Comment by Haehnchen** [comment]
this line was removed, its much easier now :)
there is now also an example inside the readme: https://github.com/Haehnchen/crypto-trading-bot#full-trade-example
