### ISSUE TITLE
EsLint on Idea, lots of red

### ISSUE THREAD

**Issue by dawez** [Haehnchen/crypto-trading-bot#109]
I am total in favour of using EsLint to keep the code quality high [that was implemented in #89 ]. However when I open the project using  intelliJ and use the `.eslintrc` I have lot of errors shown in the code. For example after some navigation on files [just exploring] I end up adding this to the `.eslintrc` to have less "red" in the code:

```
    "class-methods-use-this": "off",
    "no-useless-constructor": "off",
    "radix": "off",
    "no-empty-function": "off",
    "no-continue": "off",
    "no-restricted-syntax": "off",
    "no-shadow": "warn",
    "no-async-promise-executor": "warn",
    "no-await-in-loop": "warn",
    "no-throw-literal": "warn",
    "no-underscore-dangle": "warn",
    "default-case": "warn",
    "no-param-reassign": "warn",
    "prefer-rest-params": "warn",
    "guard-for-in": "off"
``` 
Is `.eslintrc` too strict at the moment then? Note that I can still see lot of places that show errors. 
Should just disable the inspector? I wonder if the other developers are enabling this setting then.

**Comment by egisz** [comment]
I also get lots of eslint errors on line endings :(
As I understand project files are saved in windows style ("CRLF"), but eslint is configured to check for unix style line endings.
![image](https://user-images.githubusercontent.com/1941760/80093164-ae923100-856c-11ea-928c-8a5171823e9a.png)

```
$ ./node_modules/.bin/eslint --print-config src/modules/system/system_util.js | grep "linebreak-style"  -A5
    "linebreak-style": [
      "off",
      "unix"
    ],
```
I propose to change eslint rule to windows  linebrake-style

**Comment by Haehnchen** [comment]
there till some linter issues, but no prority to fix them. its done step by step as working on it. moreover a proper IDE would be helpful which will help on lineending ;)
