### ISSUE TITLE
Binance Bot Haehanchen Installation in Termux   

### ISSUE THREAD

**Issue by Nai-mul** [Haehnchen/crypto-trading-bot#121]
A heartfelt thank you to the developer for giving us a gift (Haechnchen bot). I was just amazed to see pictures of it and so far i haven’t used it. Unfortunately, there are no complete instructions for installing this software. I tried to install it in Termux following the approach of Linux but failed everytime  :(
Can Someone help me by uploading this installation video Youtube? Please...

**Comment by nickmitchko** [comment]
Hi @Nai-mul, I do not think you can get this running on termux. Does termux have a nodejs distribution? If so, you can probably get it hacked up to run, however, it's probably a lost cause given termux being an android hosted shell.

If you have access to an old computer, I find the performance fine on older machines and you can leave it as your trading server.

**Comment by Nai-mul** [comment]
Thanks...
