### ISSUE TITLE
Backtesting : percentage of profits and losses

### ISSUE THREAD

**Issue by Gabri** [Haehnchen/crypto-trading-bot#14]
Hello,
Very impressive work! (I've just discovered this project)

I think a little but useful improvement to the backtesting feature is to show the percentage of profit & losses of the total signals thrown (excluding eventual leverage to take it simple).
I'll study a bit the project and I think I'll made a pull request for this ..if already not done ;)

Thanks

**Comment by Haehnchen** [comment]
yes indeed thats missing and on my todo list.

**Comment by Haehnchen** [comment]
Profits are no implemented see screenshot:
![foobar55](https://user-images.githubusercontent.com/1011712/103083180-13aa9480-45dc-11eb-8f5a-6c8b390d76a1.png)
