### ISSUE TITLE
Error on tick_listener.js (?)

### ISSUE THREAD

**Issue by Gabri** [Haehnchen/crypto-trading-bot#15]
Maybe it's just a configuration problem.
Anyway I had some errors on console like these:
(node:4052) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at instances.symbols.filter (/home/gabri/sources/git/crypto-trading-bot/modules/listener/tick_listener.js:98:91)...
So the problem, in my case, is that some symbol.trade.strategies seems not defined in some cases, I haven't investigate too much, anyway a simple fix for this exception is to add this on the lambda filter: "&& symbol.trade.strategies" before "symbol.trade.strategies.length > 0".

Thanks

PS: my instance.js is equals to instance.js.dist on repository
I'm just testing with bitmex_testnet

**Comment by Haehnchen** [comment]
oh yes this was missing. added this now
