### ISSUE TITLE
add support trailing stop and leverage to binance futures

### ISSUE THREAD

**Issue by jordanlanch** [Haehnchen/crypto-trading-bot#161]
HI, please add support trailing stop and leverage in binance futures
thanks

**Comment by jordanlanch** [comment]
Hi,:D

How to configurate trailing stop to binance futures in the file instance.js?

**Comment by kangoulya** [comment]
leverage work only with bybit and bitmex
and Since https://github.com/Haehnchen/crypto-trading-bot/commit/cd463192a5f3cc9fbca6382958f0d31fba7129dd
you can use trailing stop on binance futures :

        'watchdogs': [
          {
            'name': 'trailing_stop_market',
            'stop_market': 0.5
          }
