### ISSUE TITLE
Binance can't create any orders

### ISSUE THREAD

**Issue by Wladastic** [Haehnchen/crypto-trading-bot#162]
Signals work,
But I get this all the time:
Stoploss create{"error":{},"order":{"id":1101312760753,"symbol":"FTMUSDT","side":"long","price":"NaN","amount":1390.608,"type":"stop","options":{"close":true}}}

my instance.js:
```

var c = module.exports = {}

c.symbols = []

const InstanceUtil = require('./src/utils/instance_util');
c.init = async () => {
    c.symbols.push(...(await InstanceUtil.binanceInitSpotUsd(pair => {

            pair.watchdogs = [
                {
                    'name': 'trailing_stop',
                    'target_percent': 1.2,
                    'stop_percent': 0.5
                },
                {
                    'name': 'risk_reward_ratio',
                    'target_percent': 3,
                    'stop_percent': 3,
                }
            ]
                pair.state = 'watch';
                pair.strategies = [
                    {
                        strategy: 'macd',
                        options: {
                            period: '1h',
                        interval : '1h'
                        },
                        interval : '1h'
                    }
                ];
                pair.trade = {
                    currency_capital: 10,
                };
              
                return pair;
               
            })
        )
    );
};

```

**Comment by Wladastic** [comment]
@Haehnchen any chance for a short review?^^

**Comment by Haehnchen** [comment]
> trailing_stop Use native exchange trailing stop; if supported by exchange eg Bitfinex

So this one is not working; binance does not have this oder types.

> _'name': 'risk_reward_ratio',_

Is also not supported as they dont support this on spot and margin ;)

I guess you need something (stoploss_watch):
_stoploss_watch Close open position if ticker price falls below the percent lose; use this for exchange that dont support stop_loss order liek Binance_

Maybe consider using binance futures its more secure with its other types

**Comment by Wladastic** [comment]
ok,
I have adjusted the watchdogs to only stoploss_watch.
I do get order actions like when I had PAXGUSDT open, it kept adding orders.
But it doesn't create anything else.
Have to look into this a bit more

**Comment by Wladastic** [comment]
turned out the "strategies" are documented wrong.
It should be:

        pair.trade = {
            'currency_capital': 2,
            'strategies': [{
                'strategy': 'obv_pump_dump'
            }, {
                'strategy': 'macd',
                'interval ': '60m'

            }]
        };

not 
        pair.strategies = [{
                'strategy': 'obv_pump_dump'
            }, {
                'strategy': 'macd',
                'interval ': '60m'

            }]
