### ISSUE TITLE
"orders" tab crashes server

### ISSUE THREAD

**Issue by Wladastic** [Haehnchen/crypto-trading-bot#166]
crypto-trading-bot | {"message":"Stoploss Watcher: no entry for position: {\"symbol\":\"PAXGUSDT\",\"side\":\"long\",\"amount\":0.0007862,\"updatedAt\":\"2020-11-26T21:55:28.565Z\"}","level":"error","timestamp":"2020-11-26T21:55:28.569Z"}
crypto-trading-bot | 
crypto-trading-bot | > crypto-trading-bot@0.0.0 start /usr/src/app
crypto-trading-bot | > node index.js trade
crypto-trading-bot | 
crypto-trading-bot | Webserver listening on: 0.0.0.0:8080
crypto-trading-bot | Trade module: warmup done; starting ticks
crypto-trading-bot | 
crypto-trading-bot | /usr/src/app/node_modules/twig/twig.js:8670
crypto-trading-bot |       throw new Twig.Error('You are using Twig.js in sync mode in combination with async extensions.');
crypto-trading-bot |       ^
crypto-trading-bot | TwigException: You are using Twig.js in sync mode in combination with async extensions.
crypto-trading-bot | npm ERR! code ELIFECYCLE
crypto-trading-bot | npm ERR! errno 1
crypto-trading-bot | npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
crypto-trading-bot | npm ERR! Exit status 1
crypto-trading-bot | npm ERR! 
crypto-trading-bot | npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
crypto-trading-bot | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
crypto-trading-bot | 
crypto-trading-bot | npm ERR! A complete log of this run can be found in:
crypto-trading-bot | npm ERR!     /root/.npm/_logs/2020-11-26T21_56_04_710Z-debug.log

**Comment by egisz** [comment]
It looks like known issue and there is suggested [solution](https://github.com/twigjs/twig.js/issues/553)

**Comment by egisz** [comment]
Checked code and it is already set correctly, so it is something else:
https://github.com/Haehnchen/crypto-trading-bot/blob/62a0ad7ef12e36181cefa997e65b49c7772d2ff2/src/modules/http.js#L90-L93

**Comment by Wladastic** [comment]
latest commit fixed it.
Closed
