### ISSUE TITLE
Strategy skipped: outdated candle sticks

### ISSUE THREAD

**Issue by mrseeker** [Haehnchen/crypto-trading-bot#187]
I seem to get constantly these messages in my logs:

```Strategy skipped: outdated candle sticks: ["15m","cci","bitmex","BCHUSD"]```

Is this normal behaviour or is there something wrong?

**Comment by gelinger777** [comment]
@mrseeker  have you solved it? I have the same on bitfinex. maybe @egisz  can  spread some light.

**Comment by mrseeker** [comment]
Still open, not solved. Does not seem to impact operations though.

**Comment by Wladastic** [comment]
for me it does, I get tons of signals that are not executed as orders but only this kind of log

**Comment by gelinger777** [comment]
@egisz @Haehnchen  any idea at least why that can happen?

**Comment by Heirophant** [comment]
I was not getting these errors using a month old version. But since I updated to most recent, now I am getting them from bybit

**Comment by gelinger777** [comment]
@Heirophant  @mrseeker  @Wladastic  are you getting them all on like  same exchange? we need to find out the reason..

**Comment by mrseeker** [comment]
> @Heirophant @mrseeker @Wladastic are you getting them all on like same exchange? we need to find out the reason..

I am getting them on Bitmex, most likely related to the fact that it could not get a full list of candles. Backtested long enough and it disappeared.

**Comment by miemczyk** [comment]
Same issue here. Using FTX - PERP.

**Comment by gelinger777** [comment]
@mrseeker  do you get  trades executed?

**Comment by Haehnchen** [comment]
the logging was just added to see that a strategy is not working.

there must be a matching "periods" for the strategy. 

```
    symbol: 'ETHUSDT',
    exchange: 'binance_futures',
    periods: ['1m', '15m', '1h'], <----- 15m
    trade: {
      currency_capital: 10,
      strategies: [
        {
          strategy: 'dip_catcher',
          interval: '15m',
          options: {
            period: '15m'  <----- 15m
          }
        }
      ]
    },
```

**Comment by gelinger777** [comment]
@Haehnchen  so do I understand right the following. When there are multiple candles feeding in (1m,15m, 1h)  and only on 1 period is strategy shooted(15m)  then on another two periods of 1m and 1h it will give that specific log and no need to worry?

**Comment by Haehnchen** [comment]
no. other dont matter. only 15m is needed.

**Comment by gelinger777** [comment]
@Haehnchen  Daniel I understand . But the log Strategy skipped: outdated candle sticks  comes from where?  from other irrelevant candles?

**Comment by Haehnchen** [comment]
there are too many "candles gaps" so for security reason the strategy (only on trading; signals are still there) is not executed and therefore no trading. could be exchange connection issues, api changes and so on.

maybe the factor can be changed. there you are taking really silent pairs where possible is no trading per period, but some more context would then be helpful. which exchange, which pair, which period:

https://github.com/Haehnchen/crypto-trading-bot/blob/bd078b0612bf21e39df027798bec79e03c884024/src/utils/technical_analysis_validator.js#L4

**Comment by mrseeker** [comment]
If you say "too many candle gaps", I think I might know why: it usually happens just after a forced reboot due to disconnects from server. It is always the 15 mins candles from Bitmex, which I can't load with backfill.
Is it possible when this happens to force a backfill to get the missing trades?

**Comment by mane** [comment]
I'm experiencing the same problem using binance, the following is the configuration I am using at the moment:

```
y.forEach((pair) => {
    c.symbols.push({
        'symbol': 'BTCEUR',
        'periods': ['1m', '15m', '1h'],
        'exchange': 'binance',
        'watchdogs': [
            {
                'name': 'stoploss',
                'percent': 3,
            },
            {
                'name': 'risk_reward_ratio',
                'target_percent': 3.1,
                'stop_percent': 2.1,
            },
            {
                'name': 'stoploss_watch',
                'stop': 1.2,
            }
        ],
        'trade': {
            'currency_capital': 50
                },
          'strategies': [
              {
                  'strategy': 'cci',
                  'options': {
                    'period': '15m'
                  }
              },
              {
                  'strategy': 'obv_pump_dump'
              },
              {
                  'strategy': 'macd',
                  'options': {
                    'period': '1h'
                }
```

and the logs:

```
Strategy skipped: outdated candle sticks: ["1h","macd","binance","BTCEUR"]
Strategy skipped: outdated candle sticks: ["1h","macd","binance","BTCEUR"]
Strategy skipped: outdated candle sticks: ["1h","macd","binance","BTCEUR"]
```

**Comment by hdthuan** [comment]
I created a PR, hope it can fix this issue https://github.com/Haehnchen/crypto-trading-bot/pull/234

**Comment by egisz** [comment]
> maybe the factor can be changed. there you are taking really silent pairs where possible is no trading per period, but some more context would then be helpful. which exchange, which pair, which period:
> 

@Haehnchen, Indeed profit factor is the key here. Lowest should be slightly above 2. Let me explain why.
I tested with strategy using 30m timeframe, and interval set to 5m. 
Factor for this timeframe is lowest=1.76.
https://github.com/Haehnchen/crypto-trading-bot/blob/96751bf2ace762a872080c704b685613675bf68e/src/utils/technical_analysis_validator.js#L14-L25

Candle time is calculated from candle open, not close. So even if candle is freshly open, it's candleOpenToCurrentTime is already above 30 (max is  52.8 for 30m timeframe):

```
// test time: 
new Date()
Wed Sep 08 2021 22:02:39 GMT+0300

// last candle time
new Date(lookbackNewestFirst[0].time*1000)
Wed Sep 08 2021 21:30:00 GMT+0300

allowedOutdatedWindow
52.8
candleOpenToCurrentTime
32.06666666666667   <----- still in range, but already > 50% of allowed range.
```

but strategy keeps ticking every 5 minutes and at the end of period difference between last closed candle and current time is close to 60 minutes, and it's close to 2.
```
// check time, close to strategy end of period.
new Date()
Wed Sep 08 2021 21:55:46 GMT+0300

// last candle
new Date(lookbackNewestFirst[0].time*1000)
Wed Sep 08 2021 21:00:00 GMT+0300
factor
1.76
allowedOutdatedWindow
52.8
candleOpenToCurrentTime
56.05     <-------------- bam, value higher than allowed.
```

A work around is to set strategy interval equal to strategy period.
A fix is to increase factor to 2.

**Comment by Wladastic** [comment]
This now occurs again,
I am using Binance, my strategy is as follows:
````  pair.periods = ['1m', '15m', '60m'];

        //  if (c.symbols.length >= 10) {
        //      console.log("I think c.symbols is full: " + c.symbols.toString())
        //      return;
        //  }

        pair.watchdogs = [{
            'name': 'stoploss_watch',
            'stop': 1.2,
        }];

        // pair.exchange = 'binance';

        pair.state = 'trade';

        pair.strategies = [
        {
            strategy: 'dip_catcher',
            options: {
                "period": "15m",
                "trend_cloud_multiplier": 4,
                "hma_high_period": 3,
                "hma_high_candle_source": "high",
                "hma_low_period": 3,
                "hma_low_candle_source": "low"
              }
        }];

        pair.trade = {
            currency_capital: 20,
            strategies: [
            {
                strategy: 'dip_catcher',
                interval: '15m',
                options: {
                    "period": "15m",
                    "trend_cloud_multiplier": 4,
                    "hma_high_period": 3,
                    "hma_high_candle_source": "high",
                    "hma_low_period": 3,
                    "hma_low_candle_source": "low"
                  }
            }
            ]
        };

        return pair;

**Comment by juandelacruz-calvo** [comment]
Same here, it started happening with a 1h period and options.period

**Comment by juandelacruz-calvo** [comment]
It happened again, for some reason the candle importer stops working, I'm trying to debug if there is any uncaught exception that is causing it or if simply, in my case, the websocket connection with Binance is lost and it doesn't reconnect
