### ISSUE TITLE
Binance: order create error: -1013

### ISSUE THREAD

**Issue by mutluerol** [Haehnchen/crypto-trading-bot#200]
I have setup as like instance.js.dist_trade, but i have error as below, please help me about this error.

error | Order create canceled no exchange return | 21-01-25 19:05:17
-- | -- | --
error | Binance: order create error: -1013 | 21-01-25 19:05:17
error | Order create canceled no exchange return | 21-01-25 19:05:17
error | Binance: order create error: -1013 | 21-01-25 19:05:17
info | Risk  Reward: order create:  {"orderChange":{"price":-17.1964494,"amount":9.9959,"type":"stop"},"symbol":"DOTUSDT","exchange":"binance"} | 21-01-25 19:05:16
info | Risk  Reward: needed order change detected:  {"orderChange":{"price":-17.1964494,"amount":9.9959,"type":"stop"},"symbol":"DOTUSDT","exchange":"binance"} | 21-01-25 19:05:16
info | Risk  Reward: order create:  {"orderChange":{"price":-19.2259566,"amount":9.9959,"type":"target"},"symbol":"DOTUSDT","exchange":"binance"} | 21-01-25 19:05:16
info | Risk  Reward: needed order change detected:  {"orderChange":{"price":-19.2259566,"amount":9.9959,"type":"target"},"symbol":"DOTUSDT","exchange":"binance"} | 21-01-25 19:05:16

**Comment by gelinger777** [comment]
Have you googled? https://www.reddit.com/r/binance/comments/7ej5cn/api_error_code1013_filter_falinure_price_filter/  
1013 possibly means your order is too small.

**Comment by kaue** [comment]
same happens here, @gelinger777 any idea how to configure the order size?

**Comment by gelinger777** [comment]
@kaue  read the manual. Section Capital https://github.com/Haehnchen/crypto-trading-bot

**Comment by Wladastic** [comment]
same thing happening for me.
I don't know how to write an enum for those error codes in nodejs though to be able to map them

**Comment by mutluerol** [comment]
Thanks for all, i found my mistake at instans.js,

const c = (module.exports = {});
c.symbols = [
  {
    symbol: 'XLMUSDT',
    exchange: 'binance',
    periods: ['1m', '15m', '1h'],
    state: 'trade',
    trade: {
      currency_capital: 10,
      strategies: [
        {
          strategy: 'dip_catcher',
          interval: '15m',
          options: {
            period: '15m'
          }
        },
        {
          strategy: 'obv_pump_dump'
        }
      ]
    },
    watchdogs: [
      {
            name: 'stoploss',
            percent: 3,
      },
      {
        name: 'risk_reward_ratio',
        target_percent: 2.1,
        stop_percent: 1.1
      }
    ]
  }
