### ISSUE TITLE
Set buy BTCUSDT, but buy BTCUSDT Quarterly0326  in binance_futures

### ISSUE THREAD

**Issue by PaiizZ** [Haehnchen/crypto-trading-bot#204]
How to fix it?

c.symbols.push({
    symbol: 'BTCUSDT',  <<<< What ENUM ?
    exchange: 'binance_futures',
    ...
});

**Comment by syuza** [comment]
What version is cxtt package? You should upgrade ccxt.

```bash
$ nom upgrade ccxt
```

**Comment by PaiizZ** [comment]
@syuza thank you :)
