### ISSUE TITLE
Signals working - but not trading

### ISSUE THREAD

**Issue by Wiingy** [Haehnchen/crypto-trading-bot#24]
Hi

For some reason, signals are working fine, but the bot is not making trades on the signals?

![signals](https://user-images.githubusercontent.com/38079884/52888042-e6158880-31c5-11e9-8bc7-ae50328574fd.PNG)
![trades](https://user-images.githubusercontent.com/38079884/52888045-e9a90f80-31c5-11e9-8506-33844f39ee8a.PNG)
![pairs](https://user-images.githubusercontent.com/38079884/52888047-eada3c80-31c5-11e9-94f7-bc013bd463b8.PNG)

On the pairs page, the Strategies Column is blank?  I thought the strategies picked in **_instance.js_** should be displayed on this page, is that correct?

Not too sure if its because i am using the Bitmex Testnet or not?  I am meant to change the state from **Watch** to trade or something?

My Bitmex Test net API looks like this -

![bitmex](https://user-images.githubusercontent.com/38079884/52888353-1a3d7900-31c7-11e9-8359-b04cde091a56.PNG)

**Comment by stepandra** [comment]
same problem, what is your solution?

**Comment by danipolo** [comment]
same problem here
