### ISSUE TITLE
Unable to install properly

### ISSUE THREAD

**Issue by aaabbbbbbb** [Haehnchen/crypto-trading-bot#250]
I have been having issue installing, i keep getting error while i installing packages ("npm install --packages"). I have also downgraded my node version to 10.16.0
Please guide me through this issue!
![2021-06-24_11-52](https://user-images.githubusercontent.com/86394480/123211216-d9ff0b80-d4e2-11eb-86f7-a1c784da2742.png)
![2021-06-24_11-53](https://user-images.githubusercontent.com/86394480/123211222-dc616580-d4e2-11eb-9e59-7238cc34c833.png)

**Comment by Dreadweave** [comment]
Is there a workaround for this?

**Comment by Dreadweave** [comment]
Can someone please help me get this working?

**Comment by egisz** [comment]
Try to update file package-lock.json:
https://github.com/Haehnchen/crypto-trading-bot/blob/e7b2a7fab19b546cc30d0ea77c08d493eb3d8ce7/package-lock.json#L1511

 update version to higher version, which is still in  npmjs registry, currently lowest is: [1.40.1](https://www.npmjs.com/package/ccxt/v/1.40.1)

Then run npm install. 
Keep in mind that this version is not tested.
