### ISSUE TITLE
double "ema" not working...

### ISSUE THREAD

**Issue by Cemlik** [Haehnchen/crypto-trading-bot#253]
**    indicatorBuilder.add('ema10', 'ema', options.period, {
      length: 100
    });

    indicatorBuilder.add('ema20', 'ema', options.period, {
      length: 200
    });**

It doesn't work when I want to use 2 emas like in the example. Aren't two ema used at the same time?

**Comment by ArnisL** [comment]
You certainly can use 2 EMAs in your strategy.

Not seeing an issue with the code you  posted.

**Comment by Dreadweave** [comment]
Still no news on this one?  Is there a workaround?
