### ISSUE TITLE
TwigException

### ISSUE THREAD

**Issue by WINDY-WINDWARD** [Haehnchen/crypto-trading-bot#26]
`Error parsing twig template /home/windy/Desktop/crypto-trading-bot/templates/base.html.twig: 
TwigException: Can't access a key k on an null or undefined object.`

**Comment by lowprize** [comment]
Same here, tested on bitmex_testnet

**Comment by doftorul** [comment]
This error appears when the bot starts, give it a bit of time for warm-up.
As soon as it starts pushing the tickers, the twig error disappears.

**Comment by Haehnchen** [comment]
#101 also fixed via twig package update
