### ISSUE TITLE
StopLoss Watchdog Error 

### ISSUE THREAD

**Issue by thematz1** [Haehnchen/crypto-trading-bot#262]
Hey, I keep getting this error although my config is with the percent set to 1.8,

`Stoploss Watcher: invalid stop configuration need \"0.1\" - \"50\"","level":"error","timestamp":"2021-09-18T13:46:17.835Z"`
`{"message":"Binance: order create error: -1100","level":"error","timestamp":"2021-09-18T13:48:52.219Z"}`

Here is an example of an instance

`c.symbols.push({
    symbol: 'BNBBUSD',
    periods: ['1d'],
    exchange: 'binance',
    state: 'trade',
    trade: {
        currency_capital: 75,
    strategies: [
        {
            strategy: 'ema',
            interval: '1440m',
            options: {
                period: '1d',
                fast_period: 1,
                slow_period: 5
            }
        }
    ]}
    ,
    watchdogs: [
        {
            name: 'stoploss',
            percent:3,
        },
        {
            name: 'stoploss_watch',
              percent:1.8,
          }
        ]
        })
`

It seems the error is about an illegal character, I am wondering if i have missed something in the instance or config steps. 

I do not see any issues in the actual source code so I assume it's something I am doing. 

Further, for many symbols on the dashboard, the 24h ticker is not showing so I may have messed something up there also. 

Thank you in advance for any help.

**Comment by ArnisL** [comment]
From what I remember it might need to be `target: 1.8` instead of `percent: 1.8`.

**Comment by thematz1** [comment]
> From what I remember it might need to be `target: 1.8` instead of `percent: 1.8`.

Thank you for this, I will check.
