### ISSUE TITLE
USDT perpetual pairs are invalid on bybit exchange

### ISSUE THREAD

**Issue by DerekWongJC** [Haehnchen/crypto-trading-bot#276]
Hi,

I ran into an error while putting "BTCUSDT" in the bybit exchange instance, while "BTCUSD" works fine. Is the bot only working on the inverse perpetual API?

Error shown below:

> crypto-trading-bot  | > crypto-trading-bot@0.0.0 start /usr/src/app
> 
> crypto-trading-bot  | > node index.js trade
> 
> crypto-trading-bot  | 
> 
> crypto-trading-bot  | Webserver listening on: 0.0.0.0:8080
> 
> crypto-trading-bot  | {"message":"Bybit: error {\"success\":false,\"ret_msg\":\"error:invalid filter:BTCUSDT\",\"conn_id\":\"ce591547-d4ef-4a82-9666-ce8083b94c85\",\"request\":{\"op\":\"subscribe\",\"args\":[\"klineV2.1.BTCUSDT\"]}}","level":"error","timestamp":"2021-12-10T01:50:37.627Z"}
> 
> crypto-trading-bot  | Bybit: error {"success":false,"ret_msg":"error:invalid filter:BTCUSDT","conn_id":"ce591547-d4ef-4a82-9666-ce8083b94c85","request":{"op":"subscribe","args":["klineV2.1.BTCUSDT"]}}
> 
> crypto-trading-bot  | {"message":"Bybit: error {\"success\":false,\"ret_msg\":\"error:invalid filter:BTCUSDT\",\"conn_id\":\"ce591547-d4ef-4a82-9666-ce8083b94c85\",\"request\":{\"op\":\"subscribe\",\"args\":[\"klineV2.15.BTCUSDT\"]}}","level":"error","timestamp":"2021-12-10T01:50:37.632Z"}
> 
> crypto-trading-bot  | Bybit: error {"success":false,"ret_msg":"error:invalid filter:BTCUSDT","conn_id":"ce591547-d4ef-4a82-9666-ce8083b94c85","request":{"op":"subscribe","args":["klineV2.15.BTCUSDT"]}}
> 
> crypto-trading-bot  | {"message":"Bybit: error {\"success\":false,\"ret_msg\":\"error:invalid filter:BTCUSDT\",\"conn_id\":\"ce591547-d4ef-4a82-9666-ce8083b94c85\",\"request\":{\"op\":\"subscribe\",\"args\":[\"klineV2.60.BTCUSDT\"]}}","level":"error","timestamp":"2021-12-10T01:50:37.634Z"}
> 
> crypto-trading-bot  | Bybit: error {"success":false,"ret_msg":"error:invalid filter:BTCUSDT","conn_id":"ce591547-d4ef-4a82-9666-ce8083b94c85","request":{"op":"subscribe","args":["klineV2.60.BTCUSDT"]}}
> 
> crypto-trading-bot  | {"message":"Bybit: error {\"success\":false,\"ret_msg\":\"error:invalid filter:BTCUSDT\",\"conn_id\":\"ce591547-d4ef-4a82-9666-ce8083b94c85\",\"request\":{\"op\":\"subscribe\",\"args\":[\"instrument_info.100ms.BTCUSDT\"]}}","level":"error","timestamp":"2021-12-10T01:50:37.636Z"}
> 
> crypto-trading-bot  | Bybit: error {"success":false,"ret_msg":"error:invalid filter:BTCUSDT","conn_id":"ce591547-d4ef-4a82-9666-ce8083b94c85","request":{"op":"subscribe","args":["instrument_info.100ms.BTCUSDT"]}}
> 
> crypto-trading-bot  | Bybit: Candle backfill error: {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1639101037.608458"}
> 
> crypto-trading-bot  | {"message":"Bybit Candle backfill error: {\"ret_code\":10001,\"ret_msg\":\"Param validation for 'symbol' failed on the 'symbol' tag\",\"ext_code\":\"\",\"ext_info\":\"\",\"result\":null,\"time_now\":\"1639101037.608458\"}","level":"error","timestamp":"2021-12-10T01:50:38.117Z"}
> 
> crypto-trading-bot  | Bybit: Candle backfill error: {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1639101038.731850"}
> 
> crypto-trading-bot  | {"message":"Bybit Candle backfill error: {\"ret_code\":10001,\"ret_msg\":\"Param validation for 'symbol' failed on the 'symbol' tag\",\"ext_code\":\"\",\"ext_info\":\"\",\"result\":null,\"time_now\":\"1639101038.731850\"}","level":"error","timestamp":"2021-12-10T01:50:39.240Z"}
> 
> crypto-trading-bot  | Bybit: Candle backfill error: {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1639101039.850228"}
> 
> crypto-trading-bot  | {"message":"Bybit Candle backfill error: {\"ret_code\":10001,\"ret_msg\":\"Param validation for 'symbol' failed on the 'symbol' tag\",\"ext_code\":\"\",\"ext_info\":\"\",\"result\":null,\"time_now\":\"1639101039.850228\"}","level":"error","timestamp":"2021-12-10T01:50:40.359Z"}
> 
> crypto-trading-bot exited with code 0

**Comment by DerekWongJC** [comment]
Found the issue, Klinev2 is only available for Inverse perpectual: https://bybit-exchange.github.io/docs/inverse/#t-websocketklinev2

**Comment by Tayeb-Ali** [comment]
> Found the issue, Klinev2 is only available for Inverse perpectual: https://bybit-exchange.github.io/docs/inverse/#t-websocketklinev2

 ok how to solve it
