### ISSUE TITLE
Order Retry with Partial Fill already happened failes

### ISSUE THREAD

**Issue by HM657** [Haehnchen/crypto-trading-bot#29]
Hi there, first of all, thank you very much for making your work open source! I really appreciated it! :-) Is there any option to send you some beers in ETH form?

I just noticed the following issue on BitMEX Testnet. A buy order with 50 contracts got filled with 5 contracts, but then the following order/price update for the rest failed due to being on the wrong side of the order book. when the software then tried to recreate the order it failed with the following message "Invalid order side: **undefined**"
Why undefined? The order itself says side:"Buy" ? See my attached screenshot.

I also noticed the new order did not take into account that from the previous order already 5 contracts had been filled? Is that correct?

![image](https://user-images.githubusercontent.com/49598473/56463271-d3bef300-639e-11e9-93ee-49dca0fb4e44.png)

**Comment by Haehnchen** [comment]
thx for this detailed reporting. i just fixed the adjust of the ordering.

about partially filled: i will implement a full "capital sync". that is never possible to buy / sell more then the configured capital. partially is just a problem on low volume pairs / exchanges. i was never running into this issue on normal pairs, but yes i will fix this.

**Comment by HM657** [comment]
Thanks a lot for the quick reply and fix!! That sounds great, looking forward to the "capital sync" feature!

**Comment by HM657** [comment]
Hey Haehnchen, quick question: with the "full capital sync" feature you mentioned, would that mean one could then also tell the system to always invest all XBT that is available? As I currently see it I always have to tell the system exactly how much currency/capital I want to invest and it is static?
If full capital sync would enable this, do you already have a rough ETA on that? :)
