### ISSUE TITLE
what is visitStrategy, visitTradeStrategy function instance for

### ISSUE THREAD

**Issue by minhphuc429** [Haehnchen/crypto-trading-bot#31]
modules/listener/tick_listener.js

```
async visitStrategy(strategy, symbol) {
    // line 23
}

async visitTradeStrategy(strategy, symbol) {
    // line 66
}
```

**Comment by Haehnchen** [comment]
visitStrategy => just for given signals
visitTradeStrategy => will live trade based on the given signals

**Comment by minhphuc429** [comment]
> visitTradeStrategy => will live trade based on the given signals

How to bot can automatically trade based on signals

**Comment by Haehnchen** [comment]
its not fully documented but the basic usage: "https://github.com/Haehnchen/crypto-trading-bot#trading"

**Comment by minhphuc429** [comment]
> its not fully documented but the basic usage: "https://github.com/Haehnchen/crypto-trading-bot#trading"

It cannot completely trade automatically but must manually manipulate at the path http://127.0.0.1:8080/pairs
