### ISSUE TITLE
Dashboard is not reading timeframes from instance.js

### ISSUE THREAD

**Issue by macd2** [Haehnchen/crypto-trading-bot#39]
When choosing in `instance.js` 
```
'periods': ['5m'],
```
than the dashboard doesn't show any data / signals and also back testing is not working without manually changing the the timeframe. 

The top bar always shows 15m and 1h no matter what is set in instanc.js
https://ibb.co/CJw41ZB

**Comment by Haehnchen** [comment]
you need to have valid candles, most exchanges dont deliver 5m. so you should use some commons. 15m, 1h. You must configure it inside the instance.js file, but still the exchanges need to support it. there is not down oder upscaling for timeframe os the dashboard whereas its possible in strategies.
