### ISSUE TITLE
bitmex 15m trading bin

### ISSUE THREAD

**Issue by doftorul** [Haehnchen/crypto-trading-bot#4]
In order to use this with Bitmex the code needs to re-construct/resample 15m timeframe from 1m bins.

Error: Unknown table for BitMEX subscription: tradeBin15m.
Available tables are announcement,connected,chat,publicNotifications,instrument,settlement,funding,insurance,liquidation,orderBookL2,orderBookL2_25,orderBook10,quote,trade,quoteBin1m,quoteBin5m,quoteBin1h,quoteBin1d,tradeBin1m,tradeBin5m,tradeBin1h,tradeBin1d,privateNotifications,account,wallet,affiliate,margin,position,transact,order,execution.

**Comment by Haehnchen** [comment]
yes resample is already in but not attached to exchanges right now, but will follow

**Comment by Haehnchen** [comment]
15m resample is now in, maybe i will provide a general resample.
also checked all indicators values, they are equal like shown on the page

**Comment by doftorul** [comment]
Thank you for fixing this !
