### ISSUE TITLE
install

### ISSUE THREAD

**Issue by fachos** [Haehnchen/crypto-trading-bot#42]
hi.. i got this problem while npm install

25 verbose stack Error: /home/pi/crypto-trading-bot/node_modules/binance-api-node: Appears to be a git repo or submodule.
25 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:137:15
25 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
25 verbose stack     at FSReqWrap.oncomplete (fs.js:154:5)
26 verbose cwd /home/pi/crypto-trading-bot
27 verbose Linux 4.14.98-v7+
28 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
29 verbose node v10.15.3
30 verbose npm  v6.4.1
31 error path /home/pi/crypto-trading-bot/node_modules/binance-api-node
32 error code EISGIT
33 error git /home/pi/crypto-trading-bot/node_modules/binance-api-node: Appears to be a git repo or submodule.
34 error git /home/pi/crypto-trading-bot/node_modules/binance-api-node
35 error git Refusing to remove it. Update manually,
35 error git or move it out of the way first.
36 verbose exit [ 1, true ]

**Comment by egisz** [comment]
It's not an issue with project. It happens when you manually git clone some repository to node_modules folder.

If you read log message it tells you to remove it from there (or delete).

You can safely delete whole node_modules folder and run npm install.

**Comment by Haehnchen** [comment]
npm; local issues. check also docker
