### ISSUE TITLE
Notify buggy with latest commit?

### ISSUE THREAD

**Issue by HM657** [Haehnchen/crypto-trading-bot#44]
I have noticed that at least for me the notifiers do not work anymore with one of the latest commits. I think it is this one: https://github.com/Haehnchen/crypto-trading-bot/commit/2cdfbc224e9d7f3a70992dec04adf66a72616803#diff-ea2e83bb6a5fc929d5a97524f4141864

It seems that the part && telegram.length > 0. (line 384) for example does not work. Same for slack etc. That way the notifiers are never started.

**Comment by HM657** [comment]
Sorry my bad I think.

**Comment by HM657** [comment]
Actually it is an issue per what I see. 
I have changed the check back to for example:
`        let slack = _.get(config, 'notify.slack');
        if (_.has(config, 'notify.slack')) {
            notifiers.push(new Slack(slack))
        }`

And now it works again.

**Comment by Haehnchen** [comment]
fixed again. the problem about `notify.slack.websocket` is provided a null for the .dist file. so i checking for webhook url too
