### ISSUE TITLE
Resampling not working correctly

### ISSUE THREAD

**Issue by HM657** [Haehnchen/crypto-trading-bot#45]
Hi there,
I have noticed the following:
Example Case Resampling 10m period (resampling from 5m) on Bitmex (implemented analog to the example for 15m)

Each time a new candle is created (every 10m), the new candle in the database table "candlesticks" will have the close value of the previous(!) 5m candle and not the actual close of the 10m period (or the second 5m candle).
This then causes follow up problems with incorrect indicators etc.
It looks to me like that the program does not have the latest 5m candles available during runtime when the resampling methods is called.

When I restart the program, it updates the candlesticks 10m period table with the lates and correct value.
Any idea what could cause this issue?

Edit: I am assuming this is related to for example Bitmex.js line around 230ff
```javascript                    // lets wait for settle down of database insert: per design we dont know when is was inserted to database
                    setTimeout(async () => {
                        if (resamples[symbol['symbol']] && resamples[symbol['symbol']][period] && resamples[symbol['symbol']][period].length > 0) {
                            for (let periodTo of resamples[symbol['symbol']][period]) {
                                await me.candlestickResample.resample(this.getName(), symbol['symbol'], period, periodTo, true)
                            }
                        }
                    }, 1000);```

**Comment by HM657** [comment]
I have to correct myself. I made a change to the code in another place to load up to 50000 candles from the database. This caused the later update etc. to take longer, resulting in the resampling not finding an up to date database! I reset the values to the original and it now works from what I can see.

**Comment by HM657** [comment]
Well, sorry for the back and forth, but for me it only worked stable after changing the above timeout to 3 seconds. Maybe there is a better way to handle this, via events or similar? :)

**Comment by HM657** [comment]
I was able to solve the first issue (10m candles with outdated data from the previous 5m candle) by increasing the timeout in bitmex.js around line 230 to 5000 (from 1000). 
```javascript
                    // lets wait for settle down of database insert: per design we dont know when is was inserted to database
                    setTimeout(async () => {
                        if (resamples[symbol['symbol']] && resamples[symbol['symbol']][period] && resamples[symbol['symbol']][period].length > 0) {
                            for (let periodTo of resamples[symbol['symbol']][period]) {
                                await me.candlestickResample.resample(this.getName(), symbol['symbol'], period, periodTo, true)
                            }
                        }
                    }, 5000);
```

The second issue solution: As the database takes some time to update the resampled candle with the final data, there will be one ticker event/one execution after the 5m candle update where the system would use the then still unfinished candle for indicator calculations. I have set the strategy up to only use candles that are at least 20 seconds old. That way I ignore the unfinished candles (but don't have to wait 5m for the next update).

In general I would hope there should be a better solution to not use these long timeouts of 5 or 20 seconds! Especially when thinking about faster candles I would think this could maybe have a better solutions.
Any ideas about this?

Thank you!

**Comment by Haehnchen** [comment]
sry, yes indeed it was just a quick hack; refactored it now to use Promise under the hood.

can you maybe also check also timing issues. i think is was fixed with this commit some days ago: https://github.com/Haehnchen/crypto-trading-bot/commit/42bce1c240d4d1ebe7cb5ce08afef38b25fadb05

This resolved gabs issues on backtesting only Bitmex (i think this what you noticed)

**Comment by HM657** [comment]
Thank you for your reply! 
Unfortunately even with the newest commits it is not working. After a candle change it will still use the value from the previous 5m candle (technically the unfinished 10m candle). Instead it should only trigger the tick event when the 10m candle is completed I would say.
I think this happens because as soon as the timestamp from the unfinished/future 10m candle is in the present, it will take the value for the next tick, even though the candle is still not finished/waiting for the final update of data.

I like your change with the async handling a lot in the Bitmex.js. Looks much better than with the timeout! :) However, if I am not mistaken you only changed the initial loading of candles from the exchange to async. The regular "stream" of candles is still using the timeout (around line 250 in Bitmex.js). If that would be async as well, it would be lovely I think! :)

**Comment by HM657** [comment]
Awesome! 👏

**Comment by HM657** [comment]
It seems to me that with one of the latest commits (maybe #c33669e) , now when using a resampled time period (for example 10m), the system will work with the unfinished candle for the indicators on 5 (so at 7.35, 7.40, 7.45 etc. it will updated the loopback and the indicator values). However, it actually should only do that on 7.30, 7.40, 7.50 and so on). This is a new behavior/issue I think but a bit related to this topic.

**Comment by HM657** [comment]
Fixed this by adding the following in the candlestick_repository.js (line 11,12):

```javascript
var now = Math.round(moment.utc(new Date()) / 1000);
let sql = 'SELECT * from candlesticks where exchange = ? AND symbol = ? and period = ? and time < ' + now + ' order by time DESC LIMIT ' + limit
```


The issue that I require a 40 second threshold when using resample candles in my strategy still applies though (as the resampled candle is not finished (did not get the final update) in the moment the candle time gets current/is live.
