### ISSUE TITLE
Rate limit exceeded error message

### ISSUE THREAD

**Issue by senzacionale** [Haehnchen/crypto-trading-bot#49]
I am getting this error after 1 or 2 minutes after I start it

`Webserver listening on: 0.0.0.0:8080
WebSocket [INFO]: Connected.
Bitmex: Connection opened.
WebSocket [INFO]: Connected.
Bitmex: Connection opened.
{"op":"subscribe","args":"tradeBin1m:XBTUSD"}
{"op":"subscribe","args":"tradeBin5m:XBTUSD"}
{"op":"subscribe","args":"tradeBin1h:XBTUSD"}
{"op":"subscribe","args":"instrument:XBTUSD"}
{"op":"subscribe","args":"tradeBin1m:XBTUSD"}
{"op":"subscribe","args":"tradeBin5m:XBTUSD"}
{"op":"subscribe","args":"tradeBin1h:XBTUSD"}
{"op":"subscribe","args":"instrument:XBTUSD"}
{"op":"subscribe","args":"tradeBin1m:ETHUSD"}
{"op":"subscribe","args":"tradeBin5m:ETHUSD"}
{"op":"subscribe","args":"tradeBin1h:ETHUSD"}
{"op":"subscribe","args":"instrument:ETHUSD"}
{"op":"subscribe","args":"tradeBin1m:XBTM19"}
{"op":"subscribe","args":"tradeBin5m:XBTM19"}
{"op":"subscribe","args":"tradeBin1h:XBTM19"}
{"op":"subscribe","args":"instrument:XBTM19"}
{"op":"subscribe","args":"tradeBin1m:ETHM19"}
{"op":"subscribe","args":"tradeBin5m:ETHM19"}
{"op":"subscribe","args":"tradeBin1h:ETHM19"}
{"op":"subscribe","args":"instrument:ETHM19"}
{"op":"subscribe","args":"tradeBin1m:ADAM19"}
{"op":"subscribe","args":"tradeBin5m:ADAM19"}
{"op":"subscribe","args":"tradeBin1h:ADAM19"}
{"op":"subscribe","args":"instrument:ADAM19"}
{"op":"subscribe","args":"tradeBin1m:TRXM19"}
{"op":"subscribe","args":"tradeBin5m:TRXM19"}
{"op":"subscribe","args":"tradeBin1h:TRXM19"}
{"op":"subscribe","args":"instrument:TRXM19"}
{"op":"subscribe","args":"tradeBin1m:XRPM19"}
{"op":"subscribe","args":"tradeBin5m:XRPM19"}
{"op":"subscribe","args":"tradeBin1h:XRPM19"}
{"op":"subscribe","args":"instrument:XRPM19"}
Bitmex: Candle backfill error: {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
{"message":"Bitmex Candle backfill error: {\"error\":{\"message\":\"Rate limit exceeded, retry in 1 seconds.\",\"name\":\"RateLimitError\"}}","level":"error","timestamp":"2019-05-29T12:14:13.507Z"}
Bitmex: Candle backfill error: {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
{"message":"Bitmex Candle backfill error: {\"error\":{\"message\":\"Rate limit exceeded, retry in 1 seconds.\",\"name\":\"RateLimitError\"}}","level":"error","timestamp":"2019-05-29T12:14:15.875Z"}
Trade module: warmup done; starting ticks
Nodejs Environment detected
(node:18424) Warning: N-API is an experimental feature and could change at any time.`

**Comment by Escaliert** [comment]
m2 why?

**Comment by hatzkel** [comment]
https://www.bitmex.com/app/restAPI#Request-Rate-Limits here might be a good start. Not sure if applicable. Post if any updates.

**Comment by Haehnchen** [comment]
just too many request at the same time; already fixed by use "queue" some month again
