### ISSUE TITLE
If profit target reached, stop order not deleted

### ISSUE THREAD

**Issue by sweepglass** [Haehnchen/crypto-trading-bot#51]
{
            'name': 'risk_reward_ratio',
            'target_percent': 6,
            'stop_percent': 3,
        }

Bitmex exchange. Bot will not know that target was reached and take profit order was executed on exchenge. Stop loss order will hang forever.

**Comment by Haehnchen** [comment]
thx, that sure currently, there is no cleanup, will go next for it.

just annoying as its a reduce_only / close order so will not be triggered. if price reaches the price to its removed automatically by exchange ;)

**Comment by Haehnchen** [comment]
easier then expected, its in now
