### ISSUE TITLE
why backtest does not have a summery?

### ISSUE THREAD

**Issue by macd2** [Haehnchen/crypto-trading-bot#52]
why the backtest is missing the most essential part which is  a summery with profit/loss, max_drawdown, R/trade etc. ?

**Comment by Haehnchen** [comment]
currently i just doing backtesting the signals. yes still an open todo #14

**Comment by macd2** [comment]
no offense, but this should be top priority, since a backtest without a summery is pretty much useless.

**Comment by egisz** [comment]
Well, at first I also thought like macd2, but basically it's easier to create and test strategy on TradingView, and then replicate code here and backtest only signals.

**Comment by Haehnchen** [comment]
was implemented if ref issues
