### ISSUE TITLE
libtensorflow can't install

### ISSUE THREAD

**Issue by quomap** [Haehnchen/crypto-trading-bot#73]
Output:
* Downloading libtensorflow
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)

**Comment by mrseeker** [comment]
ECONNRESET means your connection is flaky or the server disconnected. Do you have a stable internet connection or (in case of wireless) are you far away from the router?

**Comment by Haehnchen** [comment]
npm; local issues. check also docker
