### ISSUE TITLE
Why you are checking SMAS 200 and not SMA 5,8,13

### ISSUE THREAD

**Issue by senzacionale** [Haehnchen/crypto-trading-bot#74]
Hello,

first very good app, but I would like to know why are you checking SMA 200 and SMA 50 which is considered a key indicator by traders and market analysts for determining the overall long-term market trend. Normally used for daily charts. Why are you checking this two and not SMA 5,8,13 which offers a perfect fit for day trading strategies?

**Comment by hatzkel** [comment]
The 200 is standard for figuring out the overall trend of the asset. Hence why the 200 was used. Other moving averages are for tighter time frames. This "issue" is random noise banter and a non-issue. Why did you even post this?

**Comment by senzacionale** [comment]
Because I would like to know, if Is related to trading with your app. you can mark it as question.
