### ISSUE TITLE
 I am getting this error ????

### ISSUE THREAD

**Issue by Speedevs** [Haehnchen/crypto-trading-bot#77]
![Screenshot (101)](https://user-images.githubusercontent.com/45816964/67136239-6db30b80-f21b-11e9-823a-75e4e304f603.png)

**Comment by hatzkel** [comment]
What the hell are you even trying to do....... Please use docker and follow the instructions in the readme. If you need installing docker or getting it up and running just stop what you are doing and move on. This is far beyond your capabilities and you need to build foundations of knowledge before you go trying to put a roof on it.

**Comment by Speedevs** [comment]
I am trying to run it Via nodejs for PC and run it on my laptop but when it Tries cloning the repo it has this error ine with the "npm" commands .....but The nodejs is a very great app

**Comment by hatzkel** [comment]
You have the solution. You can either listen or not and keep crying wanting a different solution and the solution is not going to change no matter how many times you ask no matter how many different places you ask. Follow the instructions.

**Comment by hatzkel** [comment]
```
cp instance.js.dist instance.js && cp conf.json.dist conf.json && sqlite3 bot.db < bot.sql
docker-compose build
docker-compose up -d
```

**Comment by Speedevs** [comment]
Thanks :)

**Comment by Speedevs** [comment]
+1

**Comment by jojoosinga** [comment]
Please close
