### ISSUE TITLE
trades are not updated from bitmex

### ISSUE THREAD

**Issue by doftorul** [Haehnchen/crypto-trading-bot#8]
localhost:8080/trades does not get populated with the existing orders on exchange.
Tested on bitmex.

**Comment by Haehnchen** [comment]
to be able to see them in general the pair must be known by the bot via `instance.js`, but fixed and support more features inside bitmex exchanges. looks now workin correctly

**Comment by doftorul** [comment]
thank you for fixing this

**Comment by doftorul** [comment]
does the bot in its current state is able to actually use the signals and launch orders on bitmex ?
