### ISSUE TITLE
Feature Request: Manual limit orders at specific prices

### ISSUE THREAD

**Issue by kyrypto** [Haehnchen/crypto-trading-bot#80]
First of all, great bot. I've found it to be a very useful tool for trading. One feature that I would love to have with the bot is create manual limit orders at specific prices with the web interface via API. Say if I want to open a long at a decided price, such as BTC at 7700. Then, for example, if the order is filled, then the bot can use strategies, or risk-reward ratio watchdog to close the trade. The current implementation with one-click orders is great, excellent for fast trades, and distant orders would make it more complete for human interaction.

**Comment by Haehnchen** [comment]
will be merged via: #93

so fare it looks like this:
![image](https://user-images.githubusercontent.com/1011712/71206411-c303ab80-22a4-11ea-9b17-d2d66c595b80.png)

will include some prices helpers:
 - like position of some sma / ems 
 - or possible fibonacci's in a time range
 - tradingview frame

**Comment by Haehnchen** [comment]
implementation merged
