### ISSUE TITLE
Config Layout error

### ISSUE THREAD

**Issue by jojoosinga** [Haehnchen/crypto-trading-bot#82]
Hi i am trying to use this with bitmex but i keep getting 

`WebSocket [ERROR]: Authentication invalid. Please check your credentials. Message: {"error":"Invalid API Key."}`  or  `(node:23553) UnhandledPromiseRejectionWarning: Invalid conf.json file. Please check: SyntaxError: Unexpected token l in JSON at position 152`

please tell me how to fix this and/or a default config

**Comment by kyrypto** [comment]
Put your API keys between quotation marks for example;
"key": "key",
"secret": "secret"
