### ISSUE TITLE
Bot doest make trades

### ISSUE THREAD

**Issue by jojoosinga** [Haehnchen/crypto-trading-bot#83]
Hi, I got the bot compiled on Linux and working API keys but the says it's trading but it's not is there something in the config. It's this for default
`y.forEach((pair) => {
    c.symbols.push({
        'symbol': pair,
        'periods': ['1m', '15m', '1h'],
        'exchange': 'bitmex',
        'state': 'watch',`

but i thought is has to be `y.forEach((pair) => {
    c.symbols.push({
        'symbol': pair,
        'periods': ['1m', '15m', '1h'],
        'exchange': 'bitmex',
        'state': 'trade',
`

**Comment by jojoosinga** [comment]
and when i do change it it gets me this
`Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD`

**Comment by hatzkel** [comment]
Because those are not their ticker symbols. XBTUSD and ETHUSD no _ inbetween. Change them in the config.

**Comment by fidel1986** [comment]
Duplicate of #27

**Comment by Haehnchen** [comment]
trade is also support; to not get confused
